name: Nome da ação

on:
  push:
    branches: main
    
jobs:
  alou:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Primeiro passo
        script_stop: true
        run: echo "hello world" \
          which python3 \
          which node \
          which docker \
          docker build -t teste . \
          docker run --rm teste \
          echo "deu tudo certo" \
          echo ${{ secrets.SUPERSECRETO }} \
          ls
