name: Nome da ação

on:
  push:
    branches: main
    
jobs:
  alou:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Primeiro passo
        run: echo "hello world"
        run: which python3
        run: which node
        run: which docker
        run: docker build -t teste .
        run: docker run --rm teste
        run: echo "deu tudo certo"
